# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

# github: [cubxxw, surftocat]
# custom: ["https://www.paypal.me/cubxxw", nsddd.top]
