# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

command:
- any: ['cmd/**/*', 'docs/commandline/**/*']

area/doc:
- any: ['docs/**/*']

faq:
- 'FAQ.md'

test:
- any: ['**/*_test.go']

e2e-test:
- any: ['test/**/*']

plugin:
- any: ['pkg/plugin/**/*']

Clusterfile:
- any: ['types/**/*']

Adopter-Info:
- 'Adopters.md'

ImageBuilding:
- any: ['build/**/*']
