# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: ✨ Feature Request
description: Suggest and idea for this project
title: "Feature: <Feature Request Title>"
labels: ["kind/feature"]
assignees:
  - kubecub/maintainers
body:
  - type: markdown
    attributes:
      value: |
        Thank you for initiating this feature request !🤗 
        Expected contribution?   📖 Read our [contributor documentation](https://github.com/kubecub/Open-IM-Server/blob/main/CONTRIBUTING.md) 
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Please check the following before submitting this feature request"
      options:
        - label: I've searched for similar issues and couldn't find anything matching
          required: true
        - label: I've discussed this feature request in the [kubecub Slack](https://join.slack.com/t/kubecub/shared_invite/zt-1se0k2bae-lkYzz0_T~BYh3rjkvlcUqQ) and got positive feedback
          required: true

  - type: dropdown
    id: problem
    attributes:
      label: Is this feature request related to a problem?
      options:
        - "✅ Yes"
        - "❎ No"
  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      value: 
        <!-- ⚠️ Please ask questions in English. Thank you -->  
      description: If yes, please provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution_description
    attributes:
      label: Solution Description
      description: A clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    id: benefits_description
    attributes:
      label: Benefits
      description: Describe the benefits this feature will bring to the project and its users
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: Potential Drawbacks
      description: Describe any potential drawbacks this feature might bring to the project and its users.
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Add any other context about your feature request here. If applicable, add drawings to help explain.
