name: Translate README

on:
  schedule:
  - cron: '0 2 * * 1'

env:
  token: "${{ secrets.BOT_GITHUB_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }} 
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Auto Translate Readme Action
        uses: kubbot/auto-translate-readme@v1.0.1
        with:
          LANG: zh-CN
      - name: Adding README - Chinese Traditional
        uses: kubbot/auto-translate-readme@v1.0.1
        with:
          LANG: zh-TW
      - name: Adding README - Hindi
        uses: kubbot/auto-translate-readme@v1.0.1
        with:
          LANG: hi
      - name: Adding README - Arabic
        uses: kubbot/auto-translate-readme@v1.0.1
        with:
          LANG: ar
      - name: Adding README - French
        uses: kubbot/auto-translate-readme@v1.0.1
        with:
          LANG: fr
