name: Translate README

on:
  push:
    branches:
      - main
      - master

env:
  token: "${{ secrets.BOT_GITHUB_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh_CN
          token: "${{ secrets.BOT_GITHUB_TOKEN }}"
      - name: Adding README - Chinese Traditional
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh_TW
          token: "${{ secrets.BOT_GITHUB_TOKEN }}"
      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: hi
          token: "${{ secrets.BOT_GITHUB_TOKEN }}"
      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ar
          token: "${{ secrets.BOT_GITHUB_TOKEN }}"
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
          token: "${{ secrets.BOT_GITHUB_TOKEN }}"
